name: clique_lucro
description: App de clique e ganhe com AdMob e Pix.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.0.1
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.0
  firebase_auth: ^4.0.0

flutter:
  uses-material-design: true